name: Next Release

on:
  repository_dispatch:
    types: ["next*"]
  workflow_dispatch:

jobs:
  static-checks:
    name: Static Checks
    uses: ./.github/workflows/static-checks.yml

  release:
    name: Release Next
    runs-on: ubuntu-latest
    needs: [static-checks]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHECKOUT_REF: ${{ github.event.client_payload.ref }}
      RELEASE_TYPE: ${{ github.event.client_payload.type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Fetch git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        
      - name: Publish Setup
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish Next
        env:
          # ensure dev dependencies are installed
          NODE_ENV: development
          NODE_AUTH_TOKEN: ${{secrets.HV_NPM_AUTOMATION_TOKEN}}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm run publish:next

  documentation:
    name: Documentation
    uses: ./.github/workflows/documentation.yml
    needs: [release]
    secrets:
      ORG_GHPAGES_DEPLOY_KEY: ${{ secrets.ORG_GHPAGES_DEPLOY_KEY }}
    with:
      publish-folder: next
