name: Next Release

on:
  repository_dispatch:
    types: ["next*"]
  workflow_dispatch:

jobs:
  static-checks:
    name: Static Checks
    uses: ./.github/workflows/static-checks.yml

  applitools:
    name: Applitools
    uses: ./.github/workflows/tests-applitools.yml
    needs: [static-checks]
    secrets:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

  release:
    name: Release Next
    runs-on: ubuntu-latest
    needs: [applitools]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHECKOUT_REF: ${{ github.event.client_payload.ref }}
      RELEASE_TYPE: ${{ github.event.client_payload.type }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Fetch git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        with:
          # Pulls all commits (needed for semantic release to correctly version)
          # See https://github.com/semantic-release/semantic-release/issues/1526
          fetch-depth: "0"
        
      - name: Publish Setup
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish Next
        env:
          NODE_AUTH_TOKEN: ${{secrets.HV_NPM_AUTOMATION_TOKEN}}
        run: |
          npm ci --include=dev 
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm run publish:next

  documentation:
    name: Documentation
    uses: ./.github/workflows/documentation.yml
    needs: [release]
    secrets:
      ORG_GHPAGES_DEPLOY_KEY: ${{ secrets.ORG_GHPAGES_DEPLOY_KEY }}
    with:
      publish-folder: next
