name: Security Scans

on:
  schedule:
    - cron: "30 6 * * 1-5" # week days at 06:30 AM
  workflow_dispatch:

jobs:
  codedx-scan:
    name: Run CodeDx Scan
    runs-on: [self-hosted, Linux]

    env:
      CODE_DX_URL: "${{ secrets.CODE_DX_URL }}"
      CODE_DX_API_KEY: ${{ secrets.CODE_DX_API_KEY }}
      CODE_DX_PROJECT_ID: 120
      DEP_CHECK_VERSION: 8.1.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Run Dependency Check Scans
        run: .github/scripts/dependency-check.sh

      - name: Archive Reports
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-reports
          path: ./reports

      - name: Upload Reports to CodeDX
        run: .github/scripts/codedx-upload.sh

  blackduck-scan:
    name: Run BlackDuck Scan
    runs-on: [self-hosted, Linux]

    env:
      PROJECT_NAME: "UI Kit"
      BLACKDUCK_VERSION: 7
      BLACKDUCK_PACKAGES_PARAM: '[{"name":"uikit-react-core", "paths":[{"path":"/packages/core/dist"}, {"path": "/packages/core/src"}], "exceptions":[{"component":"@hitachivantara/uikit-react-core"}]}]'

    steps:
      - name: Discover current branch
        run: |
          REF=$( echo "${{ github.ref }}" ) # gets the branch or tag ref that triggered the workflow (something like 'refs/heads/branch-name')
          REF=$( echo ${REF##*/} ) # removes the 'refs/heads/' reference
          echo "CURRENT_BRANCH=$REF" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: npm run build

      - name: Run Blackduck Scan
        uses: ./.github/actions/blackduck-scan
        with:
          server-url: '${{ secrets.BLACKDUCK_SERVER_URL }}'
          key: '${{ secrets.BLACKDUCK_TOKEN }}'
          version: '${{ env.CURRENT_BRANCH }}'
          packages: '${{ env.BLACKDUCK_PACKAGES_PARAM }}'
